// solo-vocab.js — GENERATED by research/wjd-mine.py. Do not edit by hand.
//
// Measured from the Weimar Jazz Database: 456 hand-transcribed jazz
// solos with note-level pitch, timing, chords and manual phrase annotation.
// These are the numbers the generator used to guess at — how far a real line
// steps, how long it runs in one direction, how many beats a phrase lasts, how
// often a note on the beat is a chord tone — taken from the players themselves.
//
// Weimar Jazz Database, The Jazzomat Research Project, Hochschule fur Musik
// Franz Liszt Weimar. Open Data Commons Open Database License (ODbL 1.0):
// https://jazzomat.hfm-weimar.de/  — attribution and share-alike apply to this
// derived data. Styles with no WJD source (monk, silver) keep their
// hand-authored numbers; the corpus transcribes single-line wind and guitar
// solos, so pianists and chord-melody guitar are simply not in it — and neither
// is any singer, which is why the "singer" profile below is measured from the
// EsAC folk song database (7,352 sung melodies) instead. Also Jazzomat, also ODbL.

export const WJD = {
  "all": {
    "chordToneOffBeat": 48.2,
    "chordToneOnBeat": 51.5,
    "descending": 49.8,
    "dirRun4plus": 13.8,
    "ioi": {
      "e8": 57.1,
      "h": 1.8,
      "long": 0.5,
      "q": 9.8,
      "s16": 14.0,
      "t16": 16.7
    },
    "leap": 12.7,
    "licks": [
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 99,
        "steps": [
          0,
          1,
          2,
          -3,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 79,
        "steps": [
          0,
          3,
          -3,
          1,
          2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 74,
        "steps": [
          0,
          2,
          -3,
          1,
          2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 60,
        "steps": [
          0,
          -2,
          1,
          -1,
          -1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 58,
        "steps": [
          0,
          -1,
          -1,
          4,
          -2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 57,
        "steps": [
          0,
          -2,
          -1,
          3,
          -2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 51,
        "steps": [
          0,
          -2,
          1,
          -2,
          -1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 50,
        "steps": [
          0,
          -1,
          -1,
          2,
          -3
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 47,
        "steps": [
          0,
          2,
          1,
          -3,
          2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 47,
        "steps": [
          0,
          2,
          3,
          -3,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 45,
        "steps": [
          0,
          3,
          -3,
          1,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 43,
        "steps": [
          0,
          -3,
          1,
          1,
          -4
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 39,
        "steps": [
          0,
          -1,
          -1,
          4,
          -5
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 37,
        "steps": [
          0,
          2,
          -2,
          -1,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 37,
        "steps": [
          0,
          1,
          -3,
          2,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 37,
        "steps": [
          0,
          3,
          -2,
          2,
          2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 37,
        "steps": [
          0,
          -1,
          -2,
          1,
          -2
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 36,
        "steps": [
          0,
          1,
          -2,
          1,
          -1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 36,
        "steps": [
          0,
          2,
          1,
          -2,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 36,
        "steps": [
          0,
          3,
          -2,
          2,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 35,
        "steps": [
          0,
          -2,
          2,
          -2,
          -1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 34,
        "steps": [
          0,
          -3,
          1,
          2,
          -3
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 34,
        "steps": [
          0,
          3,
          -1,
          -2,
          1
        ]
      },
      {
        "durs": [
          0.5,
          0.5,
          0.5,
          0.5,
          1.0
        ],
        "n": 34,
        "steps": [
          0,
          3,
          -3,
          2,
          -2
        ]
      }
    ],
    "meanDirRun": 2.04,
    "mlu": {
      "expressive": 3.3,
      "lick": 48.8,
      "line_d": 2.2,
      "line_w": 12.6,
      "line_w_d": 4.3,
      "melody": 6.9
    },
    "notes": 200809,
    "notesPerPhrase": 18.6,
    "phraseBeatsMean": 9.52,
    "phraseBeatsMedian": 7.0,
    "repeat": 4.6,
    "solos": 456,
    "step": 56.1,
    "third": 26.5
  },
  "instruments": {
    "alto": {
      "chordToneOffBeat": 49.4,
      "chordToneOnBeat": 53.1,
      "descending": 50.0,
      "dirRun4plus": 14.3,
      "ioi": {
        "e8": 55.6,
        "h": 1.1,
        "long": 0.3,
        "q": 8.7,
        "s16": 17.4,
        "t16": 16.9
      },
      "leap": 13.2,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 17,
          "steps": [
            0,
            2,
            -2,
            -1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 15,
          "steps": [
            0,
            3,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 15,
          "steps": [
            0,
            1,
            2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 14,
          "steps": [
            0,
            2,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 14,
          "steps": [
            0,
            -3,
            1,
            1,
            -4
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 13,
          "steps": [
            0,
            3,
            -2,
            -1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 10,
          "steps": [
            0,
            3,
            -3,
            1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 10,
          "steps": [
            0,
            -1,
            1,
            2,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 10,
          "steps": [
            0,
            -3,
            1,
            1,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 9,
          "steps": [
            0,
            1,
            -2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 9,
          "steps": [
            0,
            -1,
            1,
            2,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 8,
          "steps": [
            0,
            -4,
            -3,
            5,
            -2
          ]
        }
      ],
      "meanDirRun": 2.09,
      "mlu": {
        "expressive": 2.8,
        "lick": 47.9,
        "line_d": 2.2,
        "line_w": 15.1,
        "line_w_d": 3.8,
        "melody": 7.7
      },
      "notes": 33501,
      "notesPerPhrase": 17.6,
      "phraseBeatsMean": 8.47,
      "phraseBeatsMedian": 6.5,
      "repeat": 3.7,
      "solos": 80,
      "step": 55.5,
      "third": 27.6
    },
    "tenor": {
      "chordToneOffBeat": 48.4,
      "chordToneOnBeat": 51.3,
      "descending": 50.2,
      "dirRun4plus": 13.7,
      "ioi": {
        "e8": 54.9,
        "h": 1.7,
        "long": 0.4,
        "q": 7.8,
        "s16": 16.2,
        "t16": 18.9
      },
      "leap": 14.1,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 48,
          "steps": [
            0,
            -1,
            -1,
            4,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 35,
          "steps": [
            0,
            -1,
            -1,
            2,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 31,
          "steps": [
            0,
            1,
            2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 29,
          "steps": [
            0,
            -2,
            -1,
            3,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 29,
          "steps": [
            0,
            3,
            -2,
            2,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 27,
          "steps": [
            0,
            2,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 25,
          "steps": [
            0,
            3,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 24,
          "steps": [
            0,
            2,
            3,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 23,
          "steps": [
            0,
            -2,
            1,
            -1,
            -1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 23,
          "steps": [
            0,
            -4,
            -3,
            5,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 21,
          "steps": [
            0,
            3,
            -2,
            2,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 20,
          "steps": [
            0,
            -2,
            1,
            -2,
            -1
          ]
        }
      ],
      "meanDirRun": 2.04,
      "mlu": {
        "expressive": 4.3,
        "lick": 45.0,
        "line_d": 2.5,
        "line_w": 12.3,
        "line_w_d": 4.7,
        "melody": 8.0
      },
      "notes": 90514,
      "notesPerPhrase": 18.4,
      "phraseBeatsMean": 8.83,
      "phraseBeatsMedian": 6.5,
      "repeat": 4.1,
      "solos": 157,
      "step": 53.8,
      "third": 28.0
    },
    "trombone": {
      "chordToneOffBeat": 49.9,
      "chordToneOnBeat": 54.4,
      "descending": 47.1,
      "dirRun4plus": 9.1,
      "ioi": {
        "e8": 58.1,
        "h": 3.0,
        "long": 0.6,
        "q": 22.1,
        "s16": 5.8,
        "t16": 10.4
      },
      "leap": 10.2,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 8,
          "steps": [
            0,
            1,
            -3,
            2,
            -4
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 7,
          "steps": [
            0,
            1,
            -3,
            2,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 5,
          "steps": [
            0,
            2,
            1,
            -3,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 5,
          "steps": [
            0,
            -3,
            2,
            1,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 5,
          "steps": [
            0,
            2,
            -3,
            1,
            -3
          ]
        },
        {
          "durs": [
            0.3333,
            0.5,
            0.5,
            0.3333,
            1.0
          ],
          "n": 5,
          "steps": [
            0,
            1,
            2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            -3,
            1,
            -3,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.3333,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            -3,
            1,
            2,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            3,
            -3,
            1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            -1,
            1,
            -3,
            3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            3,
            -1,
            1,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            2,
            1,
            -1,
            1
          ]
        }
      ],
      "meanDirRun": 1.76,
      "mlu": {
        "expressive": 2.4,
        "fragment": 2.2,
        "lick": 63.8,
        "line_a": 2.5,
        "line_i_dd": 3.1,
        "line_w": 4.7
      },
      "notes": 6488,
      "notesPerPhrase": 13.8,
      "phraseBeatsMean": 9.04,
      "phraseBeatsMedian": 7.0,
      "repeat": 11.4,
      "solos": 26,
      "step": 54.3,
      "third": 24.2
    },
    "trumpet": {
      "chordToneOffBeat": 46.7,
      "chordToneOnBeat": 50.0,
      "descending": 50.0,
      "dirRun4plus": 13.6,
      "ioi": {
        "e8": 61.7,
        "h": 2.3,
        "long": 0.7,
        "q": 12.4,
        "s16": 9.2,
        "t16": 13.7
      },
      "leap": 9.4,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 35,
          "steps": [
            0,
            1,
            2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 21,
          "steps": [
            0,
            2,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 21,
          "steps": [
            0,
            3,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 21,
          "steps": [
            0,
            -3,
            1,
            -2,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 20,
          "steps": [
            0,
            -2,
            -1,
            3,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 20,
          "steps": [
            0,
            2,
            1,
            -2,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 20,
          "steps": [
            0,
            -2,
            1,
            -1,
            -1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 19,
          "steps": [
            0,
            -2,
            1,
            -2,
            -1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 16,
          "steps": [
            0,
            1,
            -2,
            1,
            -1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 15,
          "steps": [
            0,
            3,
            -3,
            1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 14,
          "steps": [
            0,
            -1,
            -2,
            1,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 14,
          "steps": [
            0,
            -2,
            2,
            -2,
            -1
          ]
        }
      ],
      "meanDirRun": 1.98,
      "mlu": {
        "expressive": 2.6,
        "lick": 53.2,
        "line_d": 1.9,
        "line_w": 10.9,
        "line_w_d": 4.6,
        "melody": 7.4
      },
      "notes": 37821,
      "notesPerPhrase": 18.6,
      "phraseBeatsMean": 10.67,
      "phraseBeatsMedian": 7.5,
      "repeat": 6.0,
      "solos": 117,
      "step": 62.8,
      "third": 21.8
    }
  },
  "styles": {
    "parker": {
      "chordToneOffBeat": 50.5,
      "chordToneOnBeat": 57.1,
      "descending": 53.7,
      "dirRun4plus": 18.0,
      "ioi": {
        "e8": 51.2,
        "h": 0.4,
        "long": 0.1,
        "q": 4.4,
        "s16": 26.2,
        "t16": 17.6
      },
      "leap": 11.4,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 5,
          "steps": [
            0,
            -9,
            3,
            3,
            -1
          ]
        },
        {
          "durs": [
            0.25,
            0.25,
            0.25,
            0.25,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            3,
            -3,
            1,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            -3,
            -3,
            2,
            -4
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            -3,
            2,
            -4,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            2,
            -4,
            -3,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 4,
          "steps": [
            0,
            -3,
            2,
            3,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            -2,
            -1,
            3,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            3,
            -2,
            -1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            2,
            3,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.25,
            0.25,
            0.25,
            0.25,
            1.0
          ],
          "n": 3,
          "steps": [
            0,
            2,
            3,
            -3,
            1
          ]
        }
      ],
      "meanDirRun": 2.3,
      "mlu": {
        "lick": 41.2,
        "line_d": 3.6,
        "line_t_dlas": 1.7,
        "line_w": 21.3,
        "line_w_d": 4.1,
        "melody": 8.4
      },
      "notes": 5672,
      "notesPerPhrase": 18.4,
      "phraseBeatsMean": 7.65,
      "phraseBeatsMedian": 6.5,
      "repeat": 2.3,
      "solos": 17,
      "sources": [
        "Charlie Parker"
      ],
      "step": 59.1,
      "third": 27.1
    },
    "singer": {
      "leap": 9.9,
      "licks": [
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 113,
          "steps": [
            0,
            -1,
            1,
            2,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 103,
          "steps": [
            0,
            -1,
            1,
            2,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 82,
          "steps": [
            0,
            -2,
            2,
            2,
            -4
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 81,
          "steps": [
            0,
            -4,
            2,
            -3,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 76,
          "steps": [
            0,
            -1,
            1,
            -3,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 75,
          "steps": [
            0,
            -1,
            1,
            4,
            -2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 73,
          "steps": [
            0,
            -2,
            2,
            1,
            -1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 73,
          "steps": [
            0,
            2,
            -2,
            -1,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 70,
          "steps": [
            0,
            2,
            1,
            -3,
            2
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 66,
          "steps": [
            0,
            -2,
            -1,
            1,
            -3
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 60,
          "steps": [
            0,
            2,
            -2,
            2,
            1
          ]
        },
        {
          "durs": [
            0.5,
            0.5,
            0.5,
            0.5,
            1.0
          ],
          "n": 59,
          "steps": [
            0,
            1,
            -1,
            -2,
            2
          ]
        }
      ],
      "meanDirRun": 1.6,
      "notes": 357812,
      "notesPerPhrase": 8.6,
      "over7": 1.9,
      "phraseBeatsMean": 7.07,
      "phraseBeatsMedian": 6.0,
      "rangeSemitones": 12.6,
      "repeat": 21.5,
      "reversalAfterSkip": 66.2,
      "solos": 7352,
      "sources": [
        "EsAC folk song database"
      ],
      "step": 52.2,
      "third": 16.4
    }
  }
};
