// songs.js — the songbook. Add your own: append an object in the same shape.
//
//   title / composer / key      display metadata
//   bpm                         default tempo (user-adjustable)
//   style                       swing | bossa | ballad | blues | modal | latin | funk
//   timeSignature               beats per bar (4 or 3)
//   form                        display label
//   source                      URLs the changes were cross-checked against
//   note                        (optional) known variants / source disagreements
//   progression                 array of bars; each bar = array of { chord, beats }
//                               beats per bar must sum to timeSignature
//
// Chord symbols only — no melodies, lyrics, or recordings. Changes follow
// common lead-sheet practice, verified against at least two jazz-education
// sources per song (see `source`).

export const SONGS = [
  {
    title: "Autumn Leaves",
    composer: "Joseph Kosma",
    key: "G minor",
    bpm: 120,
    style: "swing",
    timeSignature: 4,
    form: "32-bar AABC",
    source: [
      "https://www.learnjazzstandards.com/blog/autumn-leaves-chords/",
      "https://jazz-circle.com/standards/autumn-leaves",
    ],
    note: "Real Book prints E minor; jam sessions and the classic recordings use G minor. Tonic bars often played Gm6.",
    progression: [
      [{ chord: "Cm7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "BbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }],
      [{ chord: "Am7b5", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "Gm7", beats: 4 }],
      [{ chord: "Cm7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "BbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }],
      [{ chord: "Am7b5", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "Gm7", beats: 4 }],
      [{ chord: "Am7b5", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "Gm7", beats: 4 }],
      [{ chord: "Cm7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "BbMaj7", beats: 4 }], [{ chord: "BbMaj7", beats: 4 }],
      [{ chord: "Am7b5", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Am7b5", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "Gm7", beats: 4 }],
    ],
  },
  {
    title: "Blue Bossa",
    composer: "Kenny Dorham",
    key: "C minor",
    bpm: 140,
    style: "bossa",
    timeSignature: 4,
    form: "16-bar AB",
    source: ["https://jazz-circle.com/standards/blue-bossa"],
    note: "Some charts hold Cm7 through bars 15-16; most jam charts use the bar-16 Dm7b5-G7 turnaround (used here).",
    progression: [
      [{ chord: "Cm7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }],
      [{ chord: "Dm7b5", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Cm7", beats: 4 }],
      [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ab7", beats: 4 }], [{ chord: "DbMaj7", beats: 4 }], [{ chord: "DbMaj7", beats: 4 }],
      [{ chord: "Dm7b5", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Dm7b5", beats: 2 }, { chord: "G7", beats: 2 }],
    ],
  },
  {
    title: "Fly Me to the Moon",
    composer: "Bart Howard",
    key: "C major",
    bpm: 120,
    style: "swing",
    timeSignature: 4,
    form: "32-bar ABAC",
    source: [
      "https://www.learnjazzstandards.com/blog/fly-me-to-the-moon-chords/",
      "https://jazz-circle.com/standards/fly-me-to-the-moon",
    ],
    note: "Harmonic-rhythm variants exist: bar 8 Am7-A7, bar 4 CMaj7-C7, bars 27-28 CMaj7-A7.",
    progression: [
      [{ chord: "Am7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "Bm7b5", beats: 4 }], [{ chord: "E7", beats: 4 }], [{ chord: "Am7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "A7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "Bm7b5", beats: 4 }], [{ chord: "E7", beats: 4 }], [{ chord: "Am7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "Em7", beats: 4 }], [{ chord: "A7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }],
    ],
  },
  {
    title: "All the Things You Are",
    composer: "Jerome Kern",
    key: "Ab major",
    bpm: 132,
    style: "swing",
    timeSignature: 4,
    form: "36-bar AABA",
    source: [
      "https://jazz-circle.com/standards/all-the-things-you-are",
      "https://bradpottermusic.wordpress.com/2015/05/16/analysis-of-jazz-standard-all-the-things-you-are/",
    ],
    note: "Bar 30 sometimes Gb7#11 instead of Dbm7; bar 24 sometimes stays EMaj7 instead of C7#5.",
    progression: [
      [{ chord: "Fm7", beats: 4 }], [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "AbMaj7", beats: 4 }],
      [{ chord: "DbMaj7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "Cm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Bb7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }],
      [{ chord: "AbMaj7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "GMaj7", beats: 4 }], [{ chord: "GMaj7", beats: 4 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "GMaj7", beats: 4 }], [{ chord: "GMaj7", beats: 4 }],
      [{ chord: "F#m7", beats: 4 }], [{ chord: "B7", beats: 4 }], [{ chord: "EMaj7", beats: 4 }], [{ chord: "C7#5", beats: 4 }],
      [{ chord: "Fm7", beats: 4 }], [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "AbMaj7", beats: 4 }],
      [{ chord: "DbMaj7", beats: 4 }], [{ chord: "Dbm7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Bdim7", beats: 4 }],
      [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Gm7b5", beats: 2 }, { chord: "C7", beats: 2 }],
    ],
  },
  {
    title: "Take the A Train",
    composer: "Billy Strayhorn",
    key: "C major",
    bpm: 160,
    style: "swing",
    timeSignature: 4,
    form: "32-bar AABA",
    source: [
      "https://antonjazz.com/2019/01/take-the-a-train-chord-changes/",
      "https://jazz-circle.com/standards/take-the-a-train",
    ],
    note: "Bars 5-6 sometimes G7#5; a Dm7-G7 turnaround is often added in bars 16/32.",
    progression: [
      [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "D7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "D7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }],
      [{ chord: "D7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "D7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
    ],
  },
  {
    title: "So What",
    composer: "Miles Davis",
    key: "D dorian",
    bpm: 136,
    style: "modal",
    timeSignature: 4,
    form: "32-bar AABA",
    source: ["https://en.wikipedia.org/wiki/So_What_(Miles_Davis_composition)"],
    note: "No functional changes — two dorian vamps: 16 bars Dm7, 8 bars Ebm7, 8 bars Dm7.",
    progression: [
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }],
      [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }], [{ chord: "Ebm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
    ],
  },
  {
    title: "Misty",
    composer: "Erroll Garner",
    key: "Eb major",
    bpm: 66,
    style: "ballad",
    timeSignature: 4,
    form: "32-bar AABA",
    source: [
      "https://jazz-circle.com/standards/misty",
      "https://www.jazz-guitar-licks.com/blog/jazz-standards/misty-erroll-garner-chord-melody-arrangement-jazz-guitar-lesson.html",
    ],
    note: "Bridge bars 21-24 vary; bar 23 sometimes Gm7b5-C7b9.",
    progression: [
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Bbm7", beats: 2 }, { chord: "Eb7", beats: 2 }], [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 2 }, { chord: "Cm7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }], [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Bbm7", beats: 2 }, { chord: "Eb7", beats: 2 }], [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 2 }, { chord: "Cm7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }],
      [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "AbMaj7", beats: 4 }], [{ chord: "AbMaj7", beats: 4 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Bbm7", beats: 2 }, { chord: "Eb7", beats: 2 }], [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }],
      [{ chord: "EbMaj7", beats: 2 }, { chord: "Cm7", beats: 2 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }],
    ],
  },
  {
    title: "Satin Doll",
    composer: "Duke Ellington & Billy Strayhorn",
    key: "C major",
    bpm: 120,
    style: "swing",
    timeSignature: 4,
    form: "32-bar AABA",
    source: [
      "https://www.learnjazzstandards.com/jazz-standards/satin-doll/",
      "https://jazz-circle.com/standards/satin-doll",
    ],
    note: "Bars 7-8 often filled with a C6-F7 / Em7-A7 turnaround instead of static CMaj7.",
    progression: [
      [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }],
      [{ chord: "Am7", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }],
      [{ chord: "Am7", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
      [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }], [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }],
      [{ chord: "Am7", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "Am7", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "G7", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }], [{ chord: "Em7", beats: 2 }, { chord: "A7", beats: 2 }],
      [{ chord: "Am7", beats: 2 }, { chord: "D7", beats: 2 }], [{ chord: "Abm7", beats: 2 }, { chord: "Db7", beats: 2 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }],
    ],
  },
  {
    title: "Summertime",
    composer: "George Gershwin",
    key: "A minor",
    bpm: 80,
    style: "ballad",
    timeSignature: 4,
    form: "16-bar",
    source: [
      "https://www.learnjazzstandards.com/blog/summertime-chords/",
      "https://jazz-circle.com/standards/summertime",
    ],
    note: "Two families of changes exist; this is the jazzier version with A7→Dm7 and D7-G7→CMaj7.",
    progression: [
      [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }], [{ chord: "Am7", beats: 4 }], [{ chord: "A7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }], [{ chord: "Am7", beats: 4 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }], [{ chord: "Am7", beats: 4 }], [{ chord: "D7", beats: 2 }, { chord: "G7", beats: 2 }],
      [{ chord: "CMaj7", beats: 4 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7", beats: 2 }],
    ],
  },
  {
    title: "Cantaloupe Island",
    composer: "Herbie Hancock",
    key: "F minor",
    bpm: 112,
    style: "funk",
    timeSignature: 4,
    form: "16-bar modal vamp",
    source: ["https://www.swiss-jazz.ch/standards-jazz/Cantaloupe.pdf"],
    progression: [
      [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }],
      [{ chord: "Db7", beats: 4 }], [{ chord: "Db7", beats: 4 }], [{ chord: "Db7", beats: 4 }], [{ chord: "Db7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Fm7", beats: 4 }],
    ],
  },
  {
    title: "The Girl from Ipanema",
    composer: "Antonio Carlos Jobim",
    key: "F major",
    bpm: 130,
    style: "bossa",
    timeSignature: 4,
    form: "40-bar AABA",
    source: [
      "https://www.learnjazzstandards.com/video/girl-from-ipanema-chords-bridge-analysis/",
      "https://musictheorymanual.com/tritone-substitution-example-4-girl-from-ipanema/",
    ],
    progression: [
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Gm7", beats: 4 }], [{ chord: "Gb7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "Gb7", beats: 4 }],
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Gm7", beats: 4 }], [{ chord: "Gb7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }],
      [{ chord: "GbMaj7", beats: 4 }], [{ chord: "GbMaj7", beats: 4 }], [{ chord: "B7", beats: 4 }], [{ chord: "B7", beats: 4 }],
      [{ chord: "F#m7", beats: 4 }], [{ chord: "F#m7", beats: 4 }], [{ chord: "D7", beats: 4 }], [{ chord: "D7", beats: 4 }],
      [{ chord: "Gm7", beats: 4 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "Eb7", beats: 4 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "D7b9", beats: 4 }], [{ chord: "Gm7", beats: 4 }], [{ chord: "C7b9", beats: 4 }],
      [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Gm7", beats: 4 }], [{ chord: "Gb7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }],
    ],
  },
  {
    title: "Black Orpheus",
    composer: "Luiz Bonfá",
    key: "A minor",
    bpm: 140,
    style: "bossa",
    timeSignature: 4,
    form: "32-bar ABAC",
    source: [
      "https://jazzleadsheet.com/post/black-orpheus/",
      "https://www.jazzingly.com/jazz-standard/manha-de-carnaval-black-orpheus",
    ],
    note: "Charts diverge more than most standards; this follows the Real Book-style chart. Bar 8 sometimes C#dim7-A7b9.",
    progression: [
      [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "A7b9", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "G7", beats: 4 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "FMaj7", beats: 4 }],
      [{ chord: "Bm7b5", beats: 4 }], [{ chord: "E7b9", beats: 4 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }],
      [{ chord: "Am7", beats: 4 }], [{ chord: "Dm7", beats: 2 }, { chord: "G7", beats: 2 }], [{ chord: "CMaj7", beats: 4 }], [{ chord: "A7b9", beats: 4 }],
      [{ chord: "Em7b5", beats: 4 }], [{ chord: "A7b9", beats: 4 }], [{ chord: "Dm7", beats: 4 }], [{ chord: "Dm7", beats: 4 }],
      [{ chord: "Dm7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }], [{ chord: "Am7", beats: 4 }], [{ chord: "Bm7b5", beats: 2 }, { chord: "E7b9", beats: 2 }],
    ],
  },
  {
    title: "Blue Monk",
    composer: "Thelonious Monk",
    key: "Bb major",
    bpm: 120,
    style: "blues",
    timeSignature: 4,
    form: "12-bar blues",
    source: ["https://www.jazzimprov.net/blog/blue-monk-chords"],
    note: "Bar 9 often subbed Cm7 (ii-V); final bar F7 as a turnaround since the tool loops.",
    progression: [
      [{ chord: "Bb7", beats: 4 }], [{ chord: "Eb7", beats: 4 }], [{ chord: "Bb7", beats: 4 }], [{ chord: "Bb7", beats: 4 }],
      [{ chord: "Eb7", beats: 4 }], [{ chord: "Edim7", beats: 4 }], [{ chord: "Bb7", beats: 4 }], [{ chord: "Bb7", beats: 4 }],
      [{ chord: "F7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "Bb7", beats: 4 }], [{ chord: "F7", beats: 4 }],
    ],
  },
  {
    title: "There Will Never Be Another You",
    composer: "Harry Warren",
    key: "Eb major",
    bpm: 160,
    style: "swing",
    timeSignature: 4,
    form: "32-bar ABAC",
    source: [
      "https://saxteacheruk.com/transcriptions/there-will-never-be-another-you/there-will-never-be-another-you-lead-sheet.html",
      "https://jazz-circle.com/standards/there-will-never-be-another-you",
    ],
    note: "The last 8 bars vary a lot between charts; this uses the textbook I-IV7-iii-VI7-ii-V turnaround.",
    progression: [
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Dm7b5", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Cm7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }],
      [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Db7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Cm7", beats: 4 }],
      [{ chord: "F7", beats: 4 }], [{ chord: "F7", beats: 4 }], [{ chord: "Fm7", beats: 4 }], [{ chord: "Bb7", beats: 4 }],
      [{ chord: "EbMaj7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Dm7b5", beats: 4 }], [{ chord: "G7", beats: 4 }],
      [{ chord: "Cm7", beats: 4 }], [{ chord: "Cm7", beats: 4 }], [{ chord: "Bbm7", beats: 4 }], [{ chord: "Eb7", beats: 4 }],
      [{ chord: "AbMaj7", beats: 4 }], [{ chord: "Db7", beats: 4 }], [{ chord: "EbMaj7", beats: 2 }, { chord: "Ab7", beats: 2 }], [{ chord: "Gm7", beats: 2 }, { chord: "C7", beats: 2 }],
      [{ chord: "Fm7", beats: 4 }], [{ chord: "Bb7", beats: 4 }], [{ chord: "EbMaj7", beats: 4 }], [{ chord: "Fm7", beats: 2 }, { chord: "Bb7", beats: 2 }],
    ],
  },
];
